### ISSUE TITLE
Functionality When Using Alternate File Tree / Explorer

### ISSUE THREAD

**Issue by jamesg546** [turulix/obsidian-folder-index#11]
I really like this plugin and I use it in my system. The only issue is that is seems to only generate the index when you click on the folder within the built-in file tree. If you click on a folder using an alternative like the File Tree Alternative Plugin, it does not create the index and you have to switch over to the default one. Would it be difficult to make the plugin function in alterate file trees/system explorers? Thank you for sharing you work.

**Comment by turulix** [comment]
I'll check it out once I have time to continue working on this project :)

**Comment by turulix** [comment]
File Tree Alternative is now competable ;)
