### ISSUE TITLE
FR: Always show folder note in Reading view mode

### ISSUE THREAD

**Issue by redactedscribe** [turulix/obsidian-folder-index#13]
It would be great if the folder notes could be forced to always display in the Reading view mode because for those of us who use the Editing view mode in _Source_ mode by default (not Live Preview), the MOC always shows up with the fenced code block on display, which isn't very useful. If the viewing mode could be toggled back to whatever it was before viewing the folder note when moving away from the folder note too, that would be prefect.

Edit: Perhaps the forcing of the viewing mode could be an option between Reading view mode and Editing mode in Live Preview mode?

Thanks!

**Comment by turulix** [comment]
I added this feature in v1.0.6 feel free to give me some feedback on it!

**Comment by redactedscribe** [comment]
I've turned the feature on and it's working like expected. Thanks, appreciated.

Although, one thing that I've noticed is that when in the graph view and you click on a folder note, the folder note won't automatically display in the reading view mode, which it should be doing I presume.

**Comment by turulix** [comment]
Okay, thank you. I'll take another look later / tmr
