### ISSUE TITLE
Default initial content suggestion

### ISSUE THREAD

**Issue by redactedscribe** [turulix/obsidian-folder-index#16]
It might be a good idea to change the Initial Content feature into a togglable one. This way you could provide a suggested initial content for users to enable, such as:

````markdown
---
tags: MOCs
---

# MOC: {{folder}}

---

```folder-index-content
```
````

I don't know whether it should be enabled by default but I can see some people wanting these index files tagged as a MOCs so that they can explore them all (or negate them with `-tag:#MOCs`) in the graph for example.

`{{folder}}` would be a special keyword that you handle which displays the folder's name and keeps it up-to-date on folder name changes. Perhaps the keyword needs a prefix to give it a namespace of sorts to avoid potential conflicts with other plugins? Not really necessary, but it could be nice that the page specifically says MOC at the top so that you immediately know what you're looking at.

1.0.6

**Comment by turulix** [comment]
Keeping the folder name uptodate is a little more complicated as I can't ensure that someone changes the title themselfs or something like that. But yes the current initial content needs improving.

**Comment by redactedscribe** [comment]
Thanks!
