### ISSUE TITLE
Does not work on the phone. 

### ISSUE THREAD

**Issue by qtozdec** [turulix/obsidian-folder-index#19]
There are also no settings on the phone

**Comment by yushaw** [comment]
Same problem, love your plugin, hoping it fixed asap. Thanks

**Comment by Jheschl17** [comment]
Was wondering whether there is a known workaround or update to this issue? I would be open to investigate open leads.

**Comment by turulix** [comment]
Feel free to start the investigation, i'm not using obsidian on the phone and not sure how to even start debugging there

**Comment by kuzmandi** [comment]
Same here. Does nothing if used on phone (Android).

**Comment by Jack-Chronicle** [comment]
was really liking how it worked and looked on my laptop but was sad to see it didn't work on mobile, i do most of my work on my tablet and it doesn't do anything

hope you can figure out a way to fix that, or find someone who can help with it

**Comment by turulix** [comment]
Can someone give me an example of a working plugin on the phone? That it doesn't even load the settings is very weird.

**Comment by Jack-Chronicle** [comment]
I'm using the plugin "Waypoint" as an alternative right now, it works a bit differently than yours but it works on mobile.

**Comment by daxmonson** [comment]
Works great on desktop, not on mobile. Staying away from similar like Waypoint because it's missing some features adds excess to work.

**Comment by highcat** [comment]
Same for me. Doesn't work on mobile (Android).

**Comment by ashmys** [comment]
Hmm it's might be the problem with main.js? The way you import function is different from waypoint plugin. Maybe try to contact them and see how they do it? 

Waypoint plugin use main.js and manifest.json only. As far as i know

**Comment by tralce** [comment]
Any updates on this? I'd really love to switch to this plugin!

**Comment by turulix** [comment]
Sadly not. As i don't know how to start debugging the issue. Any help would be appreciated

**Comment by sherer-pro** [comment]
For Android:

1. Enable Developer Mode on your Android device: Go to `Settings > About phone > Build` number and tap on the build number several times until you see a message that Developer Mode is enabled.
2. In `Settings > Developer` options, enable USB debugging.
3. Connect the Android device to your computer using a USB cable.
4. Open the Chrome browser on your computer and go to `chrome://inspect`.
5. In the Devices section, your Android device should appear. Find the open page with Obsidian and click on `Inspect`.
6. In the DevTools window that opens, you will be able to view console logs, errors, and interact with the JavaScript code of the plugin.

For iOS:

1. Connect your iOS device to your Mac using a USB cable.
2. Open Safari on your Mac and enable the developer menu: Go to `Safari > Preferences > Advanced > Show Develop menu` in menu bar and enable the `Web Inspector` option.
3. In the developer menu of Safari, select your iOS device, where Obsidian is open.
4. In the list of available pages, select the page with Obsidian. A DevTools window will open, where you can view console logs, errors, and interact with the JavaScript code of the plugin.

**Comment by turulix** [comment]
Does version 1.0.28 work?

**Comment by tralce** [comment]
Yes, this works great. Thank you!

**Comment by turulix** [comment]
Sweet closing this issue then :D
