### ISSUE TITLE
Set file name template in settings

### ISSUE THREAD

**Issue by ameetmadan** [turulix/obsidian-folder-index#20]
I think it would be a great addition if the user can decide themself, how they want to call the index file. For me it is confusing when the index file has the same name as the folder. I am not sure what impact this has on the renaming feature, wanted to add it as a suggestion.

E.g. 

- Folder name: "Cool Obsidian Plugins"
- Settings > File name template: Index of {{folder_name}}
- Result: Index for Cool Obsidian Plugins

**Comment by turulix** [comment]
Could be implemented with #10

**Comment by kuzmandi** [comment]
This would be very helpful for me. I want to have the index file named: _{{folder_name}} and this would be possible with this enhancement.

**Comment by turulix** [comment]
I implemented #10 in 1.0.19 so you can now rename the files within the index itself, while this changes the name that appears in the Index File, it dosn't change the filename itself. There still is an issue to bring back the "hide Index file" option, but i still don't know what causes that to break :/

**Comment by brunompicinini** [comment]
Yes, this would be great! I'd love to do the same as @ameetmadan suggested! Doesn't seem to be possible at the moment without generating a new index file with the folder name.

**Comment by turulix** [comment]
just closing this so i have all the conversation in one issue #46
