### ISSUE TITLE
Problem with Table of Content displayed by IndexFile

### ISSUE THREAD

**Issue by Jun-July** [turulix/obsidian-folder-index#22]
Hi,

thank you for this plugging, it's very helpful. One drawback, however, with the table of content displayed by the automatically created IndexFile. For some reason, the headlines there are not organized in alphabetical order. Instead, the order in the headlines is defined randomly (or by a criterion I don't understand). Thanks for your help!

**Comment by turulix** [comment]
Thats actually not a stupid idea to sort them, they are currently just in the order they are discovered by the Plugin as far as i remember

**Comment by Jun-July** [comment]
another thing I am noticing is that the table of content doesn't recognize subfolders within the folder. The index only classifies files, and subfolders won't appear in it.

**Comment by turulix** [comment]
Yea thats still on my todo list

**Comment by tigrerol** [comment]
Please implement sorting, that would be awesome! Thx!

**Comment by turulix** [comment]
Sorting Alphabetically Available as of v1.0.8 :)
