### ISSUE TITLE
Subfolder aren't being displayed on the TOC of the parent folder note

### ISSUE THREAD

**Issue by qazero** [turulix/obsidian-folder-index#26]
Firstly, than you for creating this wonderful plugin, I am loving it!

I noticed that the TOC only lists notes within the same folder. But if I have a subfolder that contains additional notes, the parent TOC won't display any of these. Ideally it would be nice to be able to navigate all levels deep from the parent TOC. Would it be possible to implement this and have the plugin look recursively?

Thanks in advance for your consideration!

**Comment by turulix** [comment]
This is indeed on the todo list :)

**Comment by qazero** [comment]
Sweet! Glad to hear it. Any rough idea when you think the feature will release? Only reason I ask is so I can gauge whether or not I need to look at using something else in the interim or just wait.

**Comment by turulix** [comment]
I'm not sure yet, but soon™

**Comment by turulix** [comment]
Just as a heads up, using : in a header seems to break the link, and i don't know why. Seems to be a obsidian thing tho

**Comment by qazero** [comment]
Wow big thanks to you for the quick update. I'm excited to test out the new version but when I click on update in Obsidian it says Failed. Any ideas?

**Comment by qazero** [comment]
```java
app.js:1 Error: Request failed, status 404
    at new t (app.js:1:717762)
    at Jw (app.js:1:717954)
    at app.js:1:718631
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.installPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1```

**Comment by turulix** [comment]
That dosn't look like an issue with the Plugin itself but more like Obsidian for some reason. Just tryed it in one of my vaults and it worked without a problem

**Comment by qazero** [comment]
Works now, must have been a network issue of some sort given the 404 I was getting before. Testing it out now, thanks!

**Comment by turulix** [comment]
No problem :) Looking forward to your feedback!

**Comment by qazero** [comment]
Works great, thank you! Just a couple enhancements if possible:

1. Ability to collapse parent bullet from TOC list if there are child bullet points. Make parent bullet point bold (symbolizes folder)

2. Output to markdown list instead of code block to preserve more universal markdown format compatibility (can see Waypoint plugin for reference if it helps): https://github.com/IdreesInc/Waypoint/

**Comment by turulix** [comment]
I saw that 3rd point being added xD

**Comment by turulix** [comment]
#37 Should fix the first point.

**Comment by turulix** [comment]
#39 Fixes the 3rd point. I'l make a release once i implement 2.

**Comment by qazero** [comment]
I noticed there has been a new release (which I've updated to as well). I see that folders are now Bold thank you! Would it be possible to use the same default color scheme for the folders (blue) instead of white? Also, could you please add the option to underline folder as well?

Are the parent bullets supposed to be collapsible in this release (I wasn't able to collapse them) or is that still pending the on #2 for an upcoming release? If it hasn't been rolled out yet then no worries, just wanted to make sure. :)

I see that you have implemented #3 thank you!! :D

![image](https://user-images.githubusercontent.com/10906010/236281178-d03eafb1-20fd-4314-a297-6c4f730b0f4f.png)

**Comment by turulix** [comment]
Obsidian dosn't do the collapsing when its rendered via the current way, so this will be automatically a thing when the waypoint style rendering is implemented

**Comment by qazero** [comment]
Makes sense. Should I open a new Feature Request to track # 2 so I can follow it once it's released or do you already have an open issue for it?

Also, should I open a new FR for this too?

> Would it be possible to use the same default color scheme for the folders (blue) instead of white? Also, could you please add the option to underline folder as well?

**Comment by turulix** [comment]
Yes please, I don't think i can fix the second one :/

**Comment by qazero** [comment]
Done, thanks again for your efforts! :)
