### ISSUE TITLE
Filter for showing files

### ISSUE THREAD

**Issue by kuzmandi** [turulix/obsidian-folder-index#41]
I would like to define a overall filter setting for the type of files which are shown in the automatic index, so that I could filter out all except .md files (for example) or just show all files beginning with a special char (all files beginning with "!").

**Comment by ronny3** [comment]
*.png yes please lol. I can't use the recursive option without some possibility to ignore the 1000 unrelated mediafiles that pop up when the parser hits the Media folder.

**Comment by turulix** [comment]
This should be doable now. The Exclusion field supports full regex support and matches the entire path
