### ISSUE TITLE
Create IndexFile manually

### ISSUE THREAD

**Issue by tsuki-aci** [turulix/obsidian-folder-index#42]
Hi,

I really like the plugin, so first of all thanks for making it. 
Second, I can't find a way to create the IndexFile when I disable "Auto Create IndexFile". I can't find any toggle or command in the command palette. 
Am I missing something? 
I like how the plugin creates the index but I don't want it for all folders that I create, just for some.

Thanks

**Comment by turulix** [comment]
Just create a File with the exact same name as the Folder, and add:

<span>
```folder-index-content<br/>
```
</span>

**Comment by tsuki-aci** [comment]
Got it, thanks!  It would be nice to have a command so it can be assigned a hotkey, that would make it much quicker.
I think it should work in combination with Folder Note which has that option, so I will try that.

**Comment by turulix** [comment]
Mind making a second issue with that idea? :)

**Comment by tsuki-aci** [comment]
Sure, I've done it!
