### ISSUE TITLE
Add command for manual FolderIndex creation

### ISSUE THREAD

**Issue by tsuki-aci** [turulix/obsidian-folder-index#43]
Hi,

As mentioned in Issue #42 (https://github.com/turulix/obsidian-folder-index/issues/42), it would be nice to have a command for creating FolderIndex manually when the automatic creation is disabled. Once you can find the command in the command palette a hotkey can be assigned to quickly create the index for the desired folders.

Currently, a workaround for this is to use the Folder Note plugin where you can assign a hotkey directly in the plugin option. Instead of using Folder Note cards visualisation you can paste ```folder-index-content``` in the Initial Content box to have it launch the folder-index plugin.

**Comment by waxxxd** [comment]
@tsuki-aci, a PR has been  pushed that allows right-clicking on the folder and selecting to create index file.

@turulix Can close the issue
