### ISSUE TITLE
Option for specifying the filename of the index file

### ISSUE THREAD

**Issue by ahf** [turulix/obsidian-folder-index#46]
From my limited experience with this plug-in, it seems like it's not possible to change the behavior where the filename of the index file have to match the name of the directory it belongs to.

This plug-in would become really useful together with various static website generators if it would be possible to configure, for example, that the filename of the index file is always called `_index.md`.

Having template expansion for this configuration option would be neat as well, such that the current behavior can be implemented this way merely by specifying the index filename as `{{folder}}`.

I don't think I was able to find any other issues in this issue tracker with a similar request, but I may have missed the request if it's already hidden in one of the other issues.

**Comment by Cammagno** [comment]
this will also make it compatible with folder note plugins

**Comment by berot3** [comment]
@Cammagno oh it isn't? What is correctly the name of the note when creating the index with this plugin?

**Comment by berot3** [comment]
> for example, that the filename of the index file is always called `_index.md`.

May I ask you which SSG you have in mind?

I think for example mkdocs allows you to specify what the name is the index-file shall be so that you cane use whatever you like.

**Comment by ahf** [comment]
@berot3 In this case it was Hugo, but I don't think this is specific to that.

Can you specify in mkdocs that the index file is named the same as the directory it belongs to?

**Comment by Cammagno** [comment]
> @Cammagno oh it isn't? What is currently the name of the note when creating the index with this plugin?

both folder note plugins give to the "folder note" the same name of the folder (with .md extension, of course)

**Comment by turulix** [comment]
The problem with this is, you don't really know, which file is the folder note otherwise. Using the folder name is a simple solution for this, and I don't really know of a easy way to fix this currently.

**Comment by Cammagno** [comment]
can't the folder 8ndex file, instead of being foldername.md (as the folder note), bee something like FI_foldetname.md or similar?
It could even be a prefix to set in plugin options, empty by default to ensure full compatibility with current behavior

**Comment by gasparschott** [comment]
I too would like the option to name the file "index.md"—or even ".index.md" (so that it would be invisible on MacOS). 

For me, the problem with naming the index file after the folder is that often my files within the folder also use the folder name in their names as a way of sorting. The index file then gets thrown in with the rest, which can be confusing and inelegant when browsing the folders with other apps.

Thanks.

**Comment by Jamalam360** [comment]
I'd also like this feature

**Comment by waxxxd** [comment]
@ahf @berot3 @gasparschott @Jamalam360 Would like to let you know that I wanted this feature for myself and made a pull request that was accepted and now I see that it was a requested feature. So FYI it's available in the current version 1.0.25.

**Comment by waxxxd** [comment]
@turulix Can close this issue
