### ISSUE TITLE
Notes not being sorted/ordered correctly in TOC

### ISSUE THREAD

**Issue by qazero** [turulix/obsidian-folder-index#49]
I have enabled `Sort Files Alphabetically` in the settings, but the TOC ordering/sorting seems to be off still. Please see the screenshot below. The 1st and last 2 bullets appear out of order. Can this be fixed somehow?

![image](https://user-images.githubusercontent.com/10906010/236324538-3d74c17a-86be-44c6-9f5a-1b6b4c02fdca.png)

**Comment by turulix** [comment]
It dosn't know that "1433" shoulb be behind "21", it just checks that 1 should be before 2 and so on. Can probably be fixed, just need to check how.

**Comment by qazero** [comment]
Makes sense. The notes appear in the correct order in the sidebar on the left. Perhaps it may be easier to somehow reference the order from there (not sure if this method would be viable or not).

**Comment by turulix** [comment]
Should be fixed as of 1.0.16
