### ISSUE TITLE
Freezing connected to Obsidian v1.3 new Pinned tab  behaviour

### ISSUE THREAD

**Issue by paprikodlak** [turulix/obsidian-folder-index#51]
Hello
in Obsidian v1.3, if link in a pinned tab is clicked, it is open in a new tab.

If Folder Index plugin (v1.0.20) is enabled, Obsidian freezes after clicking on a link in a pinned tab. If I try to reopen Obsidian, it get stuck on Loading Workspace. 

After workspace.json, Obsidian launches again, and after disabling Folder Index plugin opening links works as expected.

**Comment by brunompicinini** [comment]
I was about to post about the same issue :) Indeed it happens here as well. Pin a tab > Open a new tab and when I try to close it, it all freezes.

**Comment by turulix** [comment]
Could someone provide a vault with the issue? Cant seem to be able to reproduce it xd

**Comment by VitalyyBezuglyj** [comment]
@turulix 
I have the same problem :(

Created a test repository, see attachments
[TestVault.zip](https://github.com/turulix/obsidian-folder-index/files/12138344/TestVault.zip)
 
Steps to reproduce: 
1. open the repository 
2. Enable the folder index extension
3. Pin any note
4. The workspace freezes

If the first step fails on startup - you need to manually remove the folder index extension in the `.obsidian` folder and try again

P.S. Great idea and extension, thanks!

**Comment by paulwalk** [comment]
I am seeing exactly the same issue.

Obsidian Version 1.4.16 running on a Mac.

**Comment by VitalyyBezuglyj** [comment]
I now use [this](https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin) extension, it's a bit more complex, not just index for dirs, but haven't such issues

Probably it will be useful for you~

**Comment by paulwalk** [comment]
I also tried [Obsidian Zoottelkeeper](https://github.com/turulix/obsidian-folder-index/issues/51#obsidian-zoottelkeeper) but I much prefer the simplicity of obsidian-folder-indexes (this plugin). I also found that Obsidian Zoottelkeeper can overwrite your files without warning, so I recommend that you are careful with your backups....

I would still like to see a fix to this issue - obsidian-folder-index is the plugin I would prefer to continue use!

**Comment by VitalyyBezuglyj** [comment]
Thanks for warning!

I also prefer this extension, but for me it's very difficult to work without pinned notes, so using zoottelkeeper for now

**Comment by turulix** [comment]
Thanks for the issue and sorry for the long wait. This should be fixed as of 1.0.23 please reopen the issue if it still isn't :)
