### ISSUE TITLE
Cant exclude particular subfolders

### ISSUE THREAD

**Issue by vince-p** [turulix/obsidian-folder-index#53]
I save all obsidian images in a subfolder named "attachments" within each folder.
I want to exclude items in these attachments folders from appearing in the indexes.
If I enter "attachments" in the Excluded Folders option box, that does properly exclude the top level /attachments folder.
But I cannot work out how to exclude any subfolders called 'attachments'. Entering */attachments does not work.

**Comment by turulix** [comment]
This was indeed bugged. Fixed in `1.0.21`
