### ISSUE TITLE
Error when combined with Full Calendar plugin

### ISSUE THREAD

**Issue by ThePyroTF2** [turulix/obsidian-folder-index#58]
When both the Folder Index plugin and the Full Calendar plugin are enabled, trying to open the full calendar causes Obsidian to become unresponsive.

I couldn't tell you which of the two plugins is causing this error, but it feels likely that it's this one.

**Comment by turulix** [comment]
Maybe related to #51

**Comment by turulix** [comment]
Thanks for the issue and sorry for the long wait. This should be fixed as of 1.0.23 please reopen the issue if it still isn't :)
