### ISSUE TITLE
[Bug] Dashboard Index file empty

### ISSUE THREAD

**Issue by zenminimalist** [turulix/obsidian-folder-index#59]
@turulix The Dashboard index file (root) does not seem to be populated. It just shows this:

![CleanShot 2023-07-30 at 20 01 41](https://github.com/turulix/obsidian-folder-index/assets/7798503/b3f719da-09b9-4624-9c84-9f07a51518c9)

Obsidian version: 1.3.5 
MacOS: 13.5

The other folder index files are generated without a problem and works.

**Comment by turulix** [comment]
Mind swapping to preview mode for me?

**Comment by zenminimalist** [comment]
> Mind swapping to preview mode for me?

Sure thing. Here you go: 

https://github.com/turulix/obsidian-folder-index/assets/7798503/18017c77-8df7-41dd-b11f-78c450cea960

**Comment by zenminimalist** [comment]
Maybe to add, a dataview query does work: 
```
dataview
List
FROM #MOCs
```
Maybe that info rules out certain things. 
I've also tried defaulting back to the default theme to rule out any conflicts. Still no success.

**Comment by turulix** [comment]
Can you show me your file structure?

**Comment by zenminimalist** [comment]
Maybe there was a misunderstanding on my side. I just happened to have put a file in the root directory yesterday and today....behold it displays exactly that. 

![CleanShot 2023-07-31 at 20 16 33](https://github.com/turulix/obsidian-folder-index/assets/7798503/4dc3dcca-575e-408a-b6a3-7be9f05d5787)

Here's my file structure:
![CleanShot 2023-07-31 at 20 16 43](https://github.com/turulix/obsidian-folder-index/assets/7798503/86dac31b-3e74-424b-8967-b948b5cbff3f)

I thought the index in the root would consolidate the MOC in the other folders so it would display a MOC of MOCs or a Index of the Indexes, which was what I was expecting. So sorry, about the confusion. My bad 😞

However, that would be a nice feature though 😇 You'd have the master index that give you a overview of all folders MOC and you can then drill down even further to the relevant file.

**Comment by turulix** [comment]
Nope, it will only display files in the `/` directory, if you want it to display all MOC files in the vault theres is a setting called `Build IndexFiles Recursively` which might do what you want :)

**Comment by zenminimalist** [comment]
> if you want it to display all MOC files in the vault theres is a setting called `Build IndexFiles Recursively` which might do what you want :)

I see, thanks. 

However, that doesn't seem to work. Or I'm missing the really obvious here (which is very likely 😇) Here's a short demo with a demo vault, of me excluding the attachment folders, but it's still displaying. I've tried a few combination, but no luck.

**Comment by turulix** [comment]
I just released a patch, try to update to version `1.0.21` and `Attachements.*?` as the exclusion

**Comment by zenminimalist** [comment]
Wow, that was fast 🤯
It doesn't seem to change the behavior. 
![CleanShot 2023-07-31 at 22 15 50@2x](https://github.com/turulix/obsidian-folder-index/assets/7798503/e31d60b7-93a5-46dd-a936-7f8ae869df07)

![CleanShot 2023-07-31 at 22 16 03@2x](https://github.com/turulix/obsidian-folder-index/assets/7798503/c9092d6e-16ef-47ca-8bfa-c3bcae859bdd)

I've also tried restarting Obsidian and deceiving and activating the recursive, no luck.

**Comment by turulix** [comment]
Umm... Now i'm kinda clueless as it works for me now and I can't reproduce it anymore

**Comment by zenminimalist** [comment]
Great, it works now! I should have caught that typo too though ☺️

One small improvement that I think would be nice is to have is to be able to collapse the lists, similar to normal md text. Here's what I mean:

![CleanShot 2023-07-31 at 22 31 56](https://github.com/turulix/obsidian-folder-index/assets/7798503/638e2352-5c67-402c-bf6b-1639241aa097)

That way, the user can see the index of indexes, but also choose to literally see every thing one numbered page (MOC and all files). Or is there an option for that too?

**Comment by turulix** [comment]
Sadly can't make the lists collapsable, since obsidian just dosn't support it for CodeBlocks, there is #48 but idk when i find motivation to implement that, that would solve this issue.

**Comment by zenminimalist** [comment]
No worries, It's a really minor thing and the plugin as whole is already such a time saver or dare I say "game changer". And the workaround for the root-level index can be a simple dataview queriy. 

Thanks again for the help and the plugin. 🤘🏽🚀
