### ISSUE TITLE
Feature Request: Index files order as Zettel's Order 

### ISSUE THREAD

**Issue by Mikeross373** [turulix/obsidian-folder-index#61]

**Comment by Mikeross373** [comment]
![image](https://github.com/turulix/obsidian-folder-index/assets/116159452/93f81f0f-c712-498f-902a-d68855b6c785)

As the picture shown, my file is sorting and named as Zettel form, which is sort from A to Z. 
The plugin did sort the other way around, and I hope to sort from A to Z

**Comment by turulix** [comment]
Yea, im aware of this. Related to #49

**Comment by turulix** [comment]
Just closing it to remove the duplicate :)
