### ISSUE TITLE
Ignore subfolders of excluded folders

### ISSUE THREAD

**Issue by Alysander** [turulix/obsidian-folder-index#65]
I have daily notes organised by year and month and would like to avoid creating index files on my daily notes within subfolders.
I think excluding subfolders of excluded folders could be a default or an option.

**Comment by turulix** [comment]
The Exclude folder option supports full Regex support on the paths of the files, maybe #59 can help you (scroll down a little) :)

**Comment by Alysander** [comment]
Thank you!
