### ISSUE TITLE
This plugin crashes Obsidian in combination with Full-Calendar-Plugin

### ISSUE THREAD

**Issue by Heiss** [turulix/obsidian-folder-index#70]
Hi,

I installed this plugin this week and since then, i had some crashes. I disabled all plugins and reenable one-by-one and after creating a sandbox vault, i had figured out, that full-calendar and folder-index does not want to play together.

I do not know, which one is the root of the problem. But both plugins works just fine, when you are using them separately. I tried some different settings, but crashes are still there. I posted this issue only in this repo, because i think that this plugin tries to do something, if there comes full-calendar view in scope, which does not live in vault / a concret folder.

**Steps to reproduce:**
1. Open the sandbox vault
2. Install and enable full-calendar and folder-index via settings
3. Open the full-calendar view while folder-index is enabled.

Do not know, how to further investigate this issue. Maybe you can point me or investigate it by yourself.

Thank you and have a great day.

**Comment by becker63** [comment]
I am experiencing the same issue

**Comment by turulix** [comment]
Thanks for the issue and sorry for the long wait. This should be fixed as of 1.0.23 please reopen the issue if it still isn't :)
