### ISSUE TITLE
Causes Obsidian to crash when closing a tab to the right of a pinned tab

### ISSUE THREAD

**Issue by wingedcatgirl** [turulix/obsidian-folder-index#72]
To replicate:

1.  Install+enable the addon
2.  Open multiple tabs
3.  Pin one of them
4.  Close the one immediately to the right of the pinned tab
5.  Crash time

It's bizarrely specific, but I did a lot of experimenting and this does it consistently

**Comment by wingedcatgirl** [comment]
Additionally, something about this crash persists between sessions and can cause Obsidian to hang on startup if it crashed at the end of last session. Force disabling the plugin by removing its folder clears this up, even if the folder is put back unchanged afterward.

**Comment by bazcurtis** [comment]
I have seen similar. If I pin a tab Obsidian will hang. I can quite it. I have to delete workspace.json and then Obsidian is responsive again

**Comment by turulix** [comment]
This should be fixed as of 1.0.23 please reopen the issue if it still isn't :)
