### ISSUE TITLE
Graph view not showing tags listed in YAML

### ISSUE THREAD

**Issue by raisabelatrix** [turulix/obsidian-folder-index#8]
If I write a tag in the body of the note, like #tag, it shows up both in local graph and in graph view.
However, if I write the tag in YAML, the tag will only show up in local graph and not in Folder Index's graph view. It shows up fine in the default graph view, though

**Comment by turulix** [comment]
Thank you for reporting this bug :) I'll take a look at it once I have time!

**Comment by turulix** [comment]
Fixed in v1.0.3

**Comment by raisabelatrix** [comment]
I'm having this problem again....
