### ISSUE TITLE
No index on iOS

### ISSUE THREAD

**Issue by GePo00** [turulix/obsidian-folder-index#85]
The plugin works great on Obsidian with PC.
But on a iPad no index will be created! Even generating a note inside a new folder with "folder-index-content" will generate a MOC?!

---
tags: MOCs
---
```folder-index-content
```

**Comment by GePo00** [comment]
This plugin uses node.js.
Therefore it doesn’t work on iOS ! 
Set "isDesktopOnly": true in the manifest.json would clarify this!!

**Comment by turulix** [comment]
fixed with #92 maybe
